version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...          
      - docker build --target ran-base --tag ran-base:latest --file docker/Dockerfile.base.ubuntu18 .
      - docker build --target ran-build --tag ran-build:latest --file docker/Dockerfile.build.ubuntu18 .
      - docker build --target oai-enb --tag oai-enb:latest --file docker/Dockerfile.eNB.ubuntu18 .
      # - docker build --target oai-lteue --tag oai-lteue:latest --file docker/Dockerfile.lteUE.ubuntu18 .
      # - docker build -t $IMAGE_REPO_NAME:$IMAGE_TAG .
      # IMAGE_REPO_NAME=oai-enb
      # IMAGE_TAG=latest
      - docker tag $IMAGE_REPO_NAME:$IMAGE_TAG $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_REPO_NAME:$IMAGE_TAG      
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image...
      - docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_REPO_NAME:$IMAGE_TAG
